version: "3.5"

services:
    database:
        image: postgres:latest
        hostname: database
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: denopg
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 5s
            timeout: 5s
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
        command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
